# Generated by Django 5.1.7 on 2025-04-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_role_role_name_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
